### ISSUE TITLE
can this programs stitch two 180°_fisheye image online?

### ISSUE THREAD

**Issue by dwx950115** [drNoob13/fisheyeStitcher#2]
can this programs stitch two 180°_fisheye image online?

**Comment by drNoob13** [comment]
This code is intended to work with 195-degree fisheyes such as ones in the Gear 360 camera. There're some hard-coded parameters that need to be changed to adapt different fovd. Regarding processing time, please refer to the readme.md.

**Comment by dwx950115** [comment]
Thank you so much for your response!
If you don’t mind, i have another questions. 
could you tell me how to creat the files in utils!
Looking forward to your response!

发自我的 iPhone

**Comment by zhuxj0416** [comment]
And how can i get an Correspondence_points_for_MLS datas for FOV200 cameras, thanks

**Comment by Gatsby23** [comment]
> Gear 360 camera

How about the latency?
