### ISSUE TITLE
could yo tell me how is the files created in "utils" ??

### ISSUE THREAD

**Issue by dwx950115** [drNoob13/fisheyeStitcher#3]
could yo tell me how is the files created in "utils" ?? 
post_find.yml
grid_xd_yd_3840x1920.yml.gz

**Comment by drNoob13** [comment]
#1

**Comment by drNoob13** [comment]
@dwx950115 Sorry for the late response. Please refer to:

_Originally posted by @drNoob13 in https://github.com/drNoob13/fisheyeStitcher/issues/1#issuecomment-498028111_
