### ISSUE TITLE
"make" problem

### ISSUE THREAD

**Issue by EadCat** [drNoob13/fisheyeStitcher#6]
hello.

I would appreciate it if you tell me how to solve it.

>>> mkdir build
==================================================================================
>>> cd build
==================================================================================
>>> cmake ..         
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_SUPPORTS_CXX17
-- Performing Test COMPILER_SUPPORTS_CXX17 - Success
-- Found OpenCV: /usr/local (found version "4.4.0") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/codes/cpp/fisheyeStitcher/build
==================================================================================
>>> make       
Scanning dependencies of target stitcher
[ 25%] Building CXX object CMakeFiles/stitcher.dir/src/fisheye_stitcher.cpp.o
/home/user/codes/cpp/fisheyeStitcher/src/fisheye_stitcher.cpp: In member function ‘cv::Mat stitcher::FisheyeStitcher::deform(const cv::Mat&)’:
/home/user/codes/cpp/fisheyeStitcher/src/fisheye_stitcher.cpp:181:51: error: ‘CV_INTER_LINEAR’ was not declared in this scope
     cv::remap(src, dst, m_mls_map_x, m_mls_map_y, CV_INTER_LINEAR, 
                                                                                  ^~~~~~~~~~~~~~~
/home/user/codes/cpp/fisheyeStitcher/src/fisheye_stitcher.cpp:181:51: note: suggested alternative: ‘CV_INLINE’
     cv::remap(src, dst, m_mls_map_x, m_mls_map_y, CV_INTER_LINEAR, 
                                                                                  ^~~~~~~~~~~~~~~
                                                                                  CV_INLINE
/home/user/codes/cpp/fisheyeStitcher/src/fisheye_stitcher.cpp: In member function ‘void stitcher::FisheyeStitcher::createBlendMask()’:
/home/user/codes/cpp/fisheyeStitcher/src/fisheye_stitcher.cpp:334:64: error: ‘CV_INTER_LINEAR’ was not declared in this scope
     cv::remap(ring_mask, ring_mask_unwarped, m_map_x, m_map_y, CV_INTER_LINEAR,
                                                                                                             ^~~~~~~~~~~~~~~
/home/user/codes/cpp/fisheyeStitcher/src/fisheye_stitcher.cpp:334:64: note: suggested alternative: ‘CV_INLINE’
     cv::remap(ring_mask, ring_mask_unwarped, m_map_x, m_map_y, CV_INTER_LINEAR,
                                                                                                             ^~~~~~~~~~~~~~~
                                                                                                             CV_INLINE
/home/user/codes/cpp/fisheyeStitcher/src/fisheye_stitcher.cpp: In member function ‘cv::Point2f stitcher::FisheyeStitcher::findMatchLoc(const cv::Mat&, const cv::Mat&, const string&, bool)’:
/home/user/codes/cpp/fisheyeStitcher/src/fisheye_stitcher.cpp:480:24: error: ‘CV_TM_CCORR_NORMED’ was not declared in this scope
     int match_method = CV_TM_CCORR_NORMED;
                                       ^~~~~~~~~~~~~~~~~~
/home/user/codes/cpp/fisheyeStitcher/src/fisheye_stitcher.cpp: In member function ‘cv::Mat stitcher::FisheyeStitcher::stitch(const cv::Mat&, const cv::Mat&)’:
/home/user/codes/cpp/fisheyeStitcher/src/fisheye_stitcher.cpp:957:29: error: ‘CV_INTER_LINEAR’ was not declared in this scope
                             CV_INTER_LINEAR);
                             ^~~~~~~~~~~~~~~
/home/user/codes/cpp/fisheyeStitcher/src/fisheye_stitcher.cpp:957:29: note: suggested alternative: ‘CV_INLINE’
                             CV_INTER_LINEAR);
                             ^~~~~~~~~~~~~~~
                             CV_INLINE
CMakeFiles/stitcher.dir/build.make:62: recipe for target 'CMakeFiles/stitcher.dir/src/fisheye_stitcher.cpp.o' failed
make[2]: *** [CMakeFiles/stitcher.dir/src/fisheye_stitcher.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/stitcher.dir/all' failed
make[1]: *** [CMakeFiles/stitcher.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

thank you.

**Comment by drNoob13** [comment]
hi, which opencv lib version are you using?

**Comment by EadCat** [comment]
I installed 4.2.0 version.
![version](https://user-images.githubusercontent.com/59416168/107175842-302a5100-6a11-11eb-8dbb-04df6dcba6e0.JPG)

**Comment by drNoob13** [comment]
I see. I tested the code with opencv3. For opencv4, can you try to replace:
```
CV_TM_CCORR_NORMED
CV_INTER_LINEAR
```
by
```
cv::TM_CCORR_NORMED
cv::INTER_LINEAR
```
Does it fix the issue?

**Comment by EadCat** [comment]
I additionally replaced
```
CV_CAP_PROP_FPS
CV_CAP_PROP_FRAME_WIDTH
CV_CAP_PROP_FRAME_HEIGHT
```
by
```
cv::CAP_PROP_FPS
cv::CAP_PROP_FRAME_WIDTH
cv::CAP_PROP_FRAME_HEIGHT
```

and finally fixed it.

Thank you so much for your help.

**Comment by utack** [comment]
Sorry to comment but shouldn't this be done in the main repo for it to be marked "solved"?
